version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "30001:80"
    depends_on:
      - db
    command: ["npm", "start"]  # Assuming your application's start command is npm start

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: sabrine_username
      MYSQL_PASSWORD: sabrine_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
