version: '3'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: sabrine_username
      MYSQL_PASSWORD: sabrine_password
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "30001:80"
    links:
      - db
